+ python Evaluation_VulBERTa-MLP.py --seed_input=666 --data_folder=fold_3_holdout --save_folder=fold_3_diverse_mlp --train_test=train --batch=8 --epochs=2 --dataset=combined
/home/<ANONYMOUS>/anaconda3/envs/myenv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/<ANONYMOUS>/anaconda3/envs/myenv/lib/python3.8/site-packages/sklearn/metrics/_classification.py:846: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
cuda
['checkpoint-22391']
models/fold_3_diverse_mlp/checkpoint-22391
124836866
Confusion matrix: 
 [[9355    0]
 [ 680    0]]

TP: 0
FP: 0
TN: 9355
FN: 680

Accuracy: 0.9322371699053313
Precision: 0.0
F-measure: 0.0
Recall: 0.0
Precision-Recall AUC: 0.06665852540068484
AUC: 0.48336246738139393
MCC: 0.0
